env: ENC[AES256_GCM,data:O2BO,iv:azpP4Hs80ZUfaG1Ft3kSsqxBahSpRVQPTrtcVsiXWNA=,tag:5qgDc5kYiArvIIoI2wml1Q==,type:str]
port: ENC[AES256_GCM,data:8cUZ,iv:+sjXsj5Chnw0oPKZPH/wYR6EBENjKhEvoCQ6M+ofqXE=,tag:aJDZs0SQwe/uGjvt8axuJg==,type:str]
debug: ENC[AES256_GCM,data:MRA2JA==,iv:RUGiuOpGxHicrb9YS+JMoGppQ0RpoKLLWFR0KPqlfSs=,tag:CHfdmOnfuhYT179y3b+mTg==,type:bool]
database:
    connectionString: ENC[AES256_GCM,data:AGKxfJnl+AXOzYzMftxQWZTdZo7OTTkt6w==,iv:yYTLBJefgjWqBCozKPZq+MSTs6vyR+G/Bg/7AXCyJ+I=,tag:5HG8n2OXnzqtxPCxyt82wg==,type:str]
    name: ENC[AES256_GCM,data:cB6gEK77,iv:DflYGe0FPc1xCkA7jtXiiW3NKiT9+EJmOqUHoWbGuIM=,tag:PXn1k10t091lLScTUWOfrg==,type:str]
    usersCollectionName: ENC[AES256_GCM,data:Q6H3LjU=,iv:d9WFhi+IVKBLfFTLo3CT0PgzthO3H7RBer6SBOk8seU=,tag:a8/ZovHAtsx9XIBIB+qc4w==,type:str]
auth:
    signingKey: ENC[AES256_GCM,data:j/jUdR2dKL2BDu8yUey+jg==,iv:Pwm8dmJeqBqIbN56Kn7wI7A60B58sD7VQgK97PlkZRI=,tag:IPulwnI/InrWp7tQGDUFog==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/mapp-254321/locations/us-west2/keyRings/mapp/cryptoKeys/config-decryption-key
        created_at: '2019-10-03T21:45:49Z'
        enc: CiQAN8LTF9K4aw+v/nf6naWXrWGYBrp3TwpVSsSQRuqpa8Bb1QUSSQDs1qoIVW06Mr2tsJHuxjF9RDrkz0l+NVweueicRTX8Sp91D0SQ6YOHFU99zZuEYORz29cOEk136pxxHAdUuiLPGE17HFm0CMc=
    azure_kv: []
    lastmodified: '2019-11-12T21:32:01Z'
    mac: ENC[AES256_GCM,data:8POUX45uoGZH4BHFcXVGPA4ts/Skc7LeyfOJX3wXDXttlKB/xrGo0u6wTrSOr5pOX+8/d/fjpqFfBbwCRBwV9bmzdQgktb/uz+NE+3a9mCJDkWvnAR/oD3V9lNA/79Gh5spExrXzN8t7zZENC5qT/6p11edxnS35snjup0fVLwY=,iv:Mp7tXo7PwePqwuqYWBJMNgtD510ckbISP+8NZnmnFMc=,tag:2TrxbjhPReE5h7VhPofbhA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.4.0
